version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/nestjs_prisma_board_ex
    overwrite: yes

permissions:
  - object: /home/ec2-user
    owner: root
    group: root
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after-deploy.sh
      timeout: 3000
      runas: root
