name: deploy

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  DAY_OF_WEEK: Monday
  Greeting: Hello
  First_Name: Mona

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
