name: deploy

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.18.1]

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check Npm -v
        run: npm -v

      - name: create env file
        working-directory: ./
        run: |
          pwd
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo REDIS_URL=${{ secrets.REDIS_URL }} >> .env
          cat .env

      - name: build server files
        working-directory: ./
        run: |
          yarn
          yarn run build

      - name: zip distributions
        run: zip -r nestjs_prisma_board_ex.zip ./

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: us-east-1

      - name: upload to S3
        run: aws s3 cp --region us-east-1 ./nestjs_prisma_board_ex.zip s3://postgresql-study/deploy/

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name postgresql-study-codedeploy
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name postgresql-study-codedeploy-group
          --s3-location bucket=postgresql-study,key=deploy/nestjs_prisma_board_ex.zip,bundleType=zip
